### ISSUE TITLE
Question: Why are the tests done over dist/ instead of src/ ?

### ISSUE THREAD

**Issue by xgbuils** [vsiakka/gherkin-lint#156]
Hi!

I found that rules are tested over `dist/`. However the rest of code is tested over `src/`. I guess that the correct way is testing over source but I would like to know if there are some reason to test rules over `dist/`.

Thanks!

**Comment by vsiakka** [comment]
The prime customer of js linting performed by eslint is the person writing the code (so they can find bugs and keep a somewhat consistent coding style), so it makes sense to test the code in the form that's the closest to the author. This is the `src` directory.

When I test the functionality of the code on the other side, I want to test the code in the form that's the closest to what the users will run. The users of the code will run the code that has been generated by babel, in the `dist` directory (src doesn't get packed in the npm module since it's not guaranteed to work with all node versions).

**Comment by xgbuils** [comment]
Ok. But after breaking node 4 support, it seems babel build process is not needed. We can pack `src` in the npm module. In this way we can guarantee tha works in all node versions.
