### ISSUE TITLE
Feature: report indentation errors sorted by line

### ISSUE THREAD

**Issue by xgbuils** [vsiakka/gherkin-lint#157]
Indentation rule don't report errors sorted by line: https://github.com/vsiakka/gherkin-lint/blob/master/test/rules/indentation/indentation.js#L10

It could be interesting fixing that.

**Comment by vsiakka** [comment]
The linter already sorts all the errors by line before passing them to the formatter, so unless you're messing with the package's internals, you should always get sorted errors in the output: https://github.com/vsiakka/gherkin-lint/blob/master/src/linter.js#L28

I prefer to keep the implementation like this because it's simple and it eliminates the room for "i forgot to implement this/implemented this wrong in X rule but all other rules work". I think it's pretty important that all rules report in a similar way when possible.

**Comment by xgbuils** [comment]
My bad, thanks.
