### ISSUE TITLE
gherkin-lint needs a maintainer

### ISSUE THREAD

**Issue by xgbuils** [vsiakka/gherkin-lint#162]
Hi,

`gherkin-lint` repo is really low maintained. I would like to start solving a lot of issues but I think it's not possible in this way. The PR #131 raises the issue that this repo is really  low tested. It doesn't make sense for me starting to fix issues without having a well tested repository.
However, having a well tested repository implies trying to isolate all the code that generates side effects(logs, interaction with the file system, etc). Some issues and PRs that I promoted (#120, #122) works in this direction. Despite this, it's difficult going forward if these issues remains freezed during more than 6 months.

Given this situation, I decided to create a new repository forked from `gherkin-lint`.
https://www.npmjs.com/package/pickle-lint
https://github.com/xgbuils/pickle-lint

Now I have 
- a 97% of code coverage.
- file system interaction is isolated into 3 files: `config-provider`, `rules-provider` and `features-provider`.
- There is only one point where application exits and logs errors.

Now, the idea is working on fixing the issues that `gherkin-lint` has. 

@vsiakka, if you are interested I can be a maintainer of this repo and merging my changes. Meanwhile, I'm working on `pickle-lint` for not keeping all of the issues freezed.

Cheers!

**Comment by vsiakka** [comment]
Hey @xgbuils I am down to make you a maintainer. How do you want to go about merging your changes to master? I commit to reviewing all the code this week (I'm down to learn from your suggestion and just have a second pair of eyes look through the changes) if that's an acceptable timeframe for you.

**Comment by xgbuils** [comment]
Hi @vsiakka

I think it's really difficult to review all my changes because I have worked [a lot](https://github.com/xgbuils/pickle-lint/commits/master):

- Added code coverage using coveralls
- Increase coverage from 56% to 97%. (from 52 to 128 tests)
- Remove babel and dist directory. Now `src/` is the code packed to npm.
- testing node 6, 8, 10 and last node version with travis ci
- update all dependencies and keep updated with [npm-check](https://www.npmjs.com/package/npm-check). No there is 0 vulnerabilities.
- add tests and refactor in functional approach all the rules (map, filter & flatMap instead of forEach). 
- As lodash is underused, I removed lodash dependency.
- one place where application exits and logs errors.
- one place where application is stylishing the output.
- file system interaction is isolated into 3 files: `config-provider`, `rules-provider` and `features-provider`.
- Fix issues #151, #154 and #163 

I can do a PR with all these changes. But I think could be a hard work for you reviewing all the code changes. I recommend you to check over the PR and download [my fork](https://github.com/xgbuils/pickle-lint/) and checking the functionality is still  working.

Take into consideration that after merging my PR, it will generate a lot of conflicts with PRs which are adding new rules to the project. I was focused to make the code more testable. Now I'm fixing the bugs I've reported the last weeks. And finally I'm going to work in adding the new features required.

Cheers!

**Comment by vsiakka** [comment]
Hey @xgbuils first off, I really appreciate all the work and interest you've put into the project.
I reviewed your code in pickle lint and I decided to not merge the 2 projects. The reasons I came to this decision are: 
- You have refactored the code to be more on the functional style. While that helps with code duplication and there are some elements I like, I think it really hurts readability. Eg the [old use-and](https://github.com/vsiakka/gherkin-lint/blob/master/src/rules/use-and.js#L3) rule seems much simpler for me to understand compared to the [new use-and](https://github.com/xgbuils/pickle-lint/blob/master/src/rules/use-and.js#L23). The old code helps me follow the data structure of the parsed feature file and I can understand exactly what it does without having to concentrate much or having to look at 3 more utility files. Coding style if of course subjective but I can't be the owner of a project with the new coding style.
- I don't think you should have removed lodash just to re-implement part of the functionality that was previously used from lodash. I think this is a con because lodash is a very well maintained, performant and documented project, it's also very popular which means that other js devs looking at lodash calls are probably somewhat familiar with the how those work/what the syntax is. Even if someoneone isn't familiar with lodash or a specific loadash function, they can go to the documentation site and use the online runner and make sure they understand it. When you redefine these functions it means anyone looking at them will have to go and look at their definition in order to understand how they work. 
- You have replaced a lot of the `for` and `foreach` loops with calls to `map`/`filter`. I believe those calls are slower((ref1)[https://dev.to/henryjw/array-map-much-slower-than-for-loop-57if], (ref2)[https://github.com/dg92/Performance-Analysis-JS]). The impact is probably small for a normal project (the number of test files and rules can't be that big) and I didn't profile pickle-lint vs gherkin-lint but i figured I'd share it in case you were interested.
- I am not a huge fan of converting everything to classes. We don't use multiple instances of any of the rules and in javascript you can't have eg a pure virtual class which each rule could inherit from in order to ensure all rules implement the same api. The might make unit testing easier, specifically setting internal state, but i think it's possible to do that testing while keeping everything in modules. I don't see a substuntial benefit in making the switch (and I like seeing every function's dependencies in it's args).
- While babel might not be necessary, I don't think negative having it in project. It enables anyone contributing to the project to write code that might not be supported by an older node version, and it takes 1-2s to run (gherkin-lint is a small project) so imo it doesn't hurt development speed significantly. If I hadn't set it up already I wouldn't do it right now, but ripping it out now is not of high importance imo and I have limited time to work on this project so I will leave this as is.
Because of all the above, I decided to not merge the projects and become more active in maintaining gherkin lint. To that I wrote test for all the rules and increased the test coverage of the whole project to a total of 95% (will merge PR shortly). I also plan on working on the reported bugs shortly.
Once again, thank you for the changes, prs, and bug reports.

**Comment by xgbuils** [comment]
Hi @vsiakka, 

It's fair. After a lot of months without mantaining actively I didn't expect that you resume the maintanance of the project soon. I'm glad to see you added a lot of code coverage. However, I recommend you to see how I managed the core code of the linter. I separated code by concerns: things like no configurable rules, configurable rules, feature provider, config provider, rules provider, formatter, etc. If you don't like classes, you could use factory functions.

Cheers!

**Comment by vsiakka** [comment]
Thanks for the pointed suggestions!

I definitely need to add/improve the formatting functionality, it's minimal atm and it looks really bad if you have even 1 long error message. I'll try to make it more eslint like and look closer to the formatters you added.

For the rest of the modules, I am not a huge fan of classes for this project because eg for a feature provider, we don't need multiple instances, it should only do work once (you get features, you're done, pass them down) so i would rather not store state. St that point (no multiple instances, not store stating) I don't think classes would bring any more value compared to modules. Additionally, by skipping the constructor and having almost a single function as each modules api, it's very easy to see the dependencies of the module in the line it's used.

I find this code very simple so i like it: 
```
var files = featureFinder.getFeatureFiles(program.args, program.ignore);
var config = configParser.getConfiguration(program.config, additionalRulesDirs);
var results = linter.lint(files, config, additionalRulesDirs);
printResults(results, program.format);
process.exit(getExitCode(results));
```
(`printResults` is atrocious and i want to deal with it when i do a formatter pass)

I will also look at the non configurable rules, see if the code can go to another place, but probably after upgrading gherkin (maybe some of the crashes are fixed 🙏 ).

I am not a js expert though, what are the benefits you think I'm missing from leaving linter, featureFinder and configParser mostly the way they are?
