### ISSUE TITLE
Upgrade to Gherkin 6

### ISSUE THREAD

**Issue by fasttime** [vsiakka/gherkin-lint#187]
Gherkin 6 has been out for more than half a year now, so I was wondering if you have any plans to upgrade your linter to use the latest Go-based version of Gherkin.

**Comment by vsiakka** [comment]
Thanks for the suggestion! I'm definitely open to upgrading and I think there is a js version of it so this could still be a pure js package: 
- https://github.com/cucumber/gherkin-javascript/
- https://www.npmjs.com/package/gherkin so this could still be a pure js package

**Comment by xgbuils** [comment]
Hi! I opened an [issue](https://github.com/cucumber/cucumber/issues/627) in gherkin project. If the parser doesn't have a good way to differentiate between simple and outline scenarios, gherkin-lint won't be able to upgrade to gherkin 6.

Cheers.

**Comment by vsiakka** [comment]
Thanks @xgbuils !

**Comment by vsiakka** [comment]
Fixed with v4.0.0 (uses Gherkin 9).


I decided to re-written the rule for `no-scenario-outlines-without-examples` using the gherkin dialects and the ast's keywords to determine when a scenario is an outline. The reason for doing is that the gherkin documentation suggests you should be using a `Scenario Outline` 
> to run the same Scenario multiple times, with different combinations of values.
even though a `Scenario` can now have examples. This is now an optional rule that someone can use because of their coding preference.
