### ISSUE TITLE
How to ignore node_module files?

### ISSUE THREAD

**Issue by djom20** [vsiakka/gherkin-lint#84]
When I try to ignore any folders o files, now the plugin add the node_modules in the list of feature to review. I try to ignore it with the .gherkin-lintignore rule but never it's happens.

**Comment by vsiakka** [comment]
Hey @djom20, sorry for the late reply. I just tested the ignore functionality again and it seems to be working for me. Make sure you use glob patterns to exclude folders though and don't pass in just a folder name. 

This is how your `.gherkin-lintignore` should look:
```
node_modules/**
```

Or if you're using the command line:
`gherkin-lint --ignore 'node_modules/**'`
Note that when using the command line you might need to add quotes around the glob pattern so that your shell doesn't evaluate the glob for you. If it does, you will probably get an error message about trying to run against the wrong file format as the shell glob will pick up all files, including eg js files.
